modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "trp"
version = "${version}"
displayName = "Tardis Refined Peripherals"
authors = "Leaf"
description = '''
Bringing ComputerCraft functionality to Tardis Refined.
'''
#logoFile = ""

[[dependencies.trp]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trp]]
modId = "architectury"
mandatory = true
versionRange = "[5.14.84,)"
ordering = "AFTER"
side = "BOTH"